"""empty message

Revision ID: 6e0e3316133f
Revises: 0a6101284767
Create Date: 2025-06-28 11:12:21.736613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0e3316133f'
down_revision = '0a6101284767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
